version: '3'
services:
  nginx:
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - inception
  wordpress:
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    # volumes:
    #   - wp:/var/www/html/
    ports:
      - "9000:9000"
    networks:
      - inception

networks:
  inception: