version: '3'
services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    ports:
      - "9000:9000"
    env_file:
      - /Users/hhamdy/Desktop/inception1/srcs/.env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb

  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    networks:
      - inception
    env_file:
      - /Users/hhamdy/Desktop/inception1/srcs/.env
    volumes:
      - mariadb:/var/lib/mysql

networks:
  inception:

volumes:
  wordpress:
    driver: local
    driver_opts:
      device: /Users/hhamdy/Desktop/inception1/volumes
      o:  bind
      type: none
  mariadb:
    driver: local
    driver_opts:
      device: /Users/hhamdy/Desktop/inception1/mariadb
      o:  bind
      type: none
