version: "3.3"
services:
  nginx:
    build: ./requirements/Nginx
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html/wordpress
    networks:
      - inception
    depends_on:
       - wordpress

  wordpress:
    build: ./requirements/Wordpress
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    volumes: 
      - wp:/var/www/html/wordpress
    env_file:
    - .env
    depends_on:
        - mariadb
  mariadb:
    build: ./requirements/MariaDB
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env

networks:
  inception:
volumes:
  wp:
    driver: local
    driver_opts:
      device: /Users/hhamdy/Desktop/inception1/volumes
      o: bind
      type: bind
  db:
    driver: local
    driver_opts:
      device: /Users/hhamdy/Desktop/inception1/mariadb
      o: bind
      type: bind