version: '3'
services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - inception
    volumes:
      - db:/var/www/html
  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    ports:
      - "9000:9000"
    volumes:
      - db:/var/www/html
    networks:
      - inception
networks:
  inception:
volumes:
  db:
    driver: local
    driver_opts:
      device: /home/hhamdy/Desktop/inception/srcs/volumes
      o:  bind
      type: none
  